version: '3.7'

services:
  fresher-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/freshermanagement
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dinhcaonhat123456789
    networks:
      - springboot-mysql-network

  mysqldb:
    image: mysql:8.0.33
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=freshermanagement
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/static/documents/database_and_collection/Database:/docker-entrypoint-initdb.d
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      retries: 10
      interval: 3s
      timeout: 30s

volumes:
  mysql-data:

networks:
  springboot-mysql-network:
    name: springboot-mysql-network
